//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBaoHanh
    {
        public int ID { get; set; }
        public string LyDoBH { get; set; }
        public int IDPhieuBaoHanh { get; set; }
    
        public virtual PhieuBaoHanh PhieuBaoHanh { get; set; }
    }
}
