//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCHLapEntities : DbContext
    {
        public QLCHLapEntities()
            : base("name=QLCHLapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HoaDonBanHang> HoaDonBanHang { get; set; }
        public virtual DbSet<HoaDonBaoHanh> HoaDonBaoHanh { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<PhieuBaoHanh> PhieuBaoHanh { get; set; }
        public virtual DbSet<PhieuNhapKho> PhieuNhapKho { get; set; }
        public virtual DbSet<PhieuXuatKho> PhieuXuatKho { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<SanPham_HoaDonBanHang> SanPham_HoaDonBanHang { get; set; }
        public virtual DbSet<SanPham_PhieuNhapKho> SanPham_PhieuNhapKho { get; set; }
        public virtual DbSet<SanPham_PhieuXuatKho> SanPham_PhieuXuatKho { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
