//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBaoHanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuBaoHanh()
        {
            this.HoaDonBaoHanh = new HashSet<HoaDonBaoHanh>();
        }
    
        public int ID { get; set; }
        public string TenSP { get; set; }
        public int ThoiHanBaoHanh { get; set; }
        public Nullable<int> IDHoaDonBanHang { get; set; }
    
        public virtual HoaDonBanHang HoaDonBanHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBaoHanh> HoaDonBaoHanh { get; set; }
    }
}
