//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_HoaDonBanHang
    {
        public int IDSanPham { get; set; }
        public int IDHoaDonBanHang { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> HoanThanh { get; set; }
    
        public virtual HoaDonBanHang HoaDonBanHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
