//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_PhieuXuatKho
    {
        public int IDSanPham { get; set; }
        public int IDPhieuXuatKho { get; set; }
        public System.DateTime NgayXuat { get; set; }
    
        public virtual PhieuXuatKho PhieuXuatKho { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
